### ISSUE TITLE
ordering of selected files

### ISSUE THREAD

**Issue by jsphweid** [denolfe/AutoHotkey#1]
Hi, this library is awesome.! Thanks.  One thing that I can't quite figure out... When using sel, it seems that the order the is retrieved from Explorer_GetSelected() depends on how you select the file.  Maybe this comes in handy for some things.  Any ideas on how I could get it to always be the same?  The order doesn't matter to me, but I do need the same order every time regardless of how it is selected.  Any ideas?

**Comment by denolfe** [comment]
Without modifying the library you could simply run this line after you get the lines back from the function:

```
Sort, sel, d`n
```

`sel` being the variable that is returned from Explorer_GetSelected()
