### ISSUE TITLE
Keyboard Layout CapsNav: Use existing layout for that, example Neo2

### ISSUE THREAD

**Issue by ypid-geberit** [denolfe/AutoHotkey#7]
Hi

Just a suggestion. I see many people reinventing their own keyboard layout because they are unhappy with the default QWERTY or QWERTZ. It might be better to use some existing reworked layout like [Neo2](https://neo-layout.org/). Note that you can still use the regular QWERTY/QWERTZ together with caps lock and all the higher layers of Neo2. You can checkout my example here: https://github.com/ypid/dotfiles/tree/master/windows/neo-vars

My point is that much more thought has been put into layouts like Neo2 compared to home-brewed layouts. I understand that for you it is probably not worth switching. I want to mention this for people who start out new.

**Comment by denolfe** [comment]
Cool, thanks for the link 👍 I'll leave this open for a bit.
