### ISSUE TITLE
"AT=" command doesn't seem to work

### ISSUE THREAD

**Issue by kahwoo** [denolfe/AutoHotkey#9]
Bug report, using the "AT=" command doesn't seem to work

Expected behaviour:
When Notification times out, AT= should trigger "MyTestLabelGoesHere" label 

Example usage:
;NotifyTest.ahk
#include Notify.ahk
Notify("Title", "testmessage",-5, "Style=Tooltip SI=50 GC=000000 TC=White MC=White SI=350 ST=450 BC=00000 GR=9 BR=13 BW=0 BT=105 TS=9 MS=8 PB=767676 GR=0 AT=MyTestLabelGoesHere ")
return

MyTestLabelGoesHere:
msgbox this message box does not show when the notification timesout
return

Am I doing this right?

**Comment by denolfe** [comment]
I have not used that option personally. Notify.ahk was a library originally pulled from [here](https://autohotkey.com/board/topic/44870-notify-multiple-easy-tray-area-notifications-v04991/). You may find some answers in that thread, though it's rather old. It looks like the author no longer uses/supports it.
